# Generated by Django 5.0.6 on 2024-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completeStatus',
            field=models.BooleanField(default=False),
        ),
    ]
