# Generated by Django 5.0.6 on 2024-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_profession_alter_user_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='designer', max_length=200),
            preserve_default=False,
        ),
    ]
