# Generated by Django 5.0.6 on 2024-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='./userProfilePhoto'),
        ),
    ]
